id-- MySQL Script generated by MySQL Workbench
-- Thu Aug 19 13:25:44 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema Language_school
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema Language_school
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `Language_school` DEFAULT CHARACTER SET utf8 ;
USE `Language_school` ;

-- -----------------------------------------------------
-- Table `Language_school`.`users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Language_school`.`users` (
  `id` BIGINT(20) NOT NULL AUTO_INCREMENT,
  `login` VARCHAR(45) NOT NULL,
  `password` VARCHAR(45) NOT NULL,
  `role` ENUM("ADMIN", "STUDENT") NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  `phone` VARCHAR(45) NOT NULL,
  `status` ENUM("INACTIVE", "ACTIVE", "BLOCKED") NOT NULL,
  UNIQUE INDEX `email_UNIQUE` (`login` ASC) VISIBLE,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Language_school`.`subscriptions`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Language_school`.`subscriptions` (
  `id` BIGINT(20) NOT NULL AUTO_INCREMENT,
  `user_id` BIGINT(20) NOT NULL,
  `date_time` DATETIME NULL,
  `status` ENUM("LIKED", "ADDED_COURSE", "ACCEPTED_TO_COURSE", "ACTIVE_COURSE", "COMPLETED_COURSE", "NOT_ACCEPTED_TO_COURSE") NOT NULL,
  `payment_method` ENUM("ERIP", "ONLINE") NULL,
  `cost` DECIMAL NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_orders_users1_idx` (`user_id` ASC) VISIBLE,
  CONSTRAINT `fk_orders_users1`
    FOREIGN KEY (`user_id`)
    REFERENCES `Language_school`.`users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Language_school`.`language`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Language_school`.`language` (
  `id` BIGINT(20) NOT NULL AUTO_INCREMENT,
  `language_name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Language_school`.`courses`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Language_school`.`courses` (
  `id` BIGINT(20) NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `price` DECIMAL NOT NULL,
  `teacher_name` VARCHAR(45) NULL,
  `language_id` BIGINT(20) NOT NULL,
  `next_start` DATE NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_courses_languages1_idx` (`language_id` ASC) VISIBLE,
  CONSTRAINT `fk_courses_languages1`
    FOREIGN KEY (`language_id`)
    REFERENCES `Language_school`.`language` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Language_school`.`subscription_course_connection`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Language_school`.`subscription_course_connection` (
  `subscriptions_id` BIGINT(20) NOT NULL,
  `courses_id` BIGINT(20) NOT NULL,
  PRIMARY KEY (`subscriptions_id`, `courses_id`),
  INDEX `fk_subscription_course_connection_sybscriptions1_idx` (`subscriptions_id` ASC) VISIBLE,
  INDEX `fk_subscription_course_connection_courses1_idx` (`courses_id` ASC) VISIBLE,
  CONSTRAINT `fk_subscription_course_connection_sybscriptions1`
    FOREIGN KEY (`subscriptions_id`)
    REFERENCES `Language_school`.`subscriptions` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_subscription_course_connection_courses1`
    FOREIGN KEY (`courses_id`)
    REFERENCES `Language_school`.`courses` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
